# Generated by Django 6.0.6 on 2026-07-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options_product_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Просмотрено'),
        ),
    ]
